# Generated by Django 4.1.2 on 2022-11-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('subtitulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('fecha_imagen', models.DateField()),
            ],
        ),
    ]
