# Generated by Django 4.1.2 on 2022-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
