# Generated by Django 4.1.2 on 2022-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0005_blogs_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
