# Generated by Django 4.1.2 on 2022-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0006_blogs_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='cuerpo',
            field=models.CharField(default='', max_length=400),
        ),
    ]
